### ISSUE TITLE
Is the machine the one our online course uses?

### ISSUE THREAD

**Issue by Jeff-Tian** [coderbunker/linux#8]
Is the machine our online course uses? Many things are different between the online courses describe and the machine I installed according to the following instructions:

```
vagrant init ubuntu/trusty64
vagrant up 
vagrant ssh
```

For example,  `ls -lF /etc/rc.d/rc5.d` returns nothing while the courses list so many...

**Comment by dulhaver** [comment]
Yes i think that's (Ubuntu 14.04) what we are using. There are quite a few things that seem to be different then in the course chapters. 
I think tue course s not 100 percent up to date.

**Comment by rosscournoyer602** [comment]
The course gives instructions for many different types of Linux systems, but sometimes gives RHEL  specific instructions and does not specify the Ubuntu equivalent. When you can't find something or the instructions don't seem to apply, just do a quick search for "How to [command/directory] in Ubuntu 14.4. You'll usually find the way to do it on our machine.

In the case of `ls -lF /etc/rc.d/rc5.d` the reason you find nothing is because those files are located in our machine under /etc

**Comment by Jeff-Tian** [comment]
Thank you @rosscournoyer602
